language: objective-c

before_install:
  - brew update
  - brew install xctool --HEAD

notifications:
  email: false

script: xctool ONLY_ACTIVE_ARCH=NO -project Demo/KoaPopover.xcodeproj -sdk iphonesimulator -scheme KoaPopover build